# Generated by Django 4.1.3 on 2022-11-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('price_title', models.CharField(max_length=50, verbose_name='price title')),
                ('price', models.PositiveIntegerField()),
                ('popular', models.BooleanField(help_text='(check)-popular')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.CharField(max_length=50, verbose_name='services')),
                ('check_close', models.BooleanField(help_text='(0)-close, (1)-check', verbose_name='check close')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.package', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
