# Generated by Django 4.1.3 on 2022-11-18 11:44

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='about title')),
                ('about_banner', models.ImageField(blank=True, null=True, upload_to='about_banner/%Y/%m/%d/', verbose_name='about banner')),
            ],
            options={
                'verbose_name': 'About Banner',
                'verbose_name_plural': 'About Banner',
            },
        ),
        migrations.CreateModel(
            name='GalleryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='sub title')),
            ],
            options={
                'verbose_name': 'gallery main',
                'verbose_name_plural': 'gallery main',
            },
        ),
        migrations.CreateModel(
            name='PopularTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(upload_to='popular_people/%Y/%m/%d/', verbose_name='1 image')),
                ('image2', models.ImageField(upload_to='popular_people2/%Y/%m/%d/', verbose_name='2 image')),
                ('started', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)], verbose_name='started')),
                ('people_about', ckeditor_uploader.fields.RichTextUploadingField(max_length=50, verbose_name='people about')),
            ],
            options={
                'verbose_name': 'Popular Trainer',
                'verbose_name_plural': 'Popular Trainers',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='about_gallery/%Y/%m/%d/', verbose_name='image')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.gallerymain')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
            },
        ),
    ]
