# Generated by Django 4.1.3 on 2022-11-24 22:23

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='about title')),
                ('about_banner', models.ImageField(blank=True, null=True, upload_to='about_banner/%Y/%m/%d/', verbose_name='about banner')),
            ],
            options={
                'verbose_name': 'About Banner',
                'verbose_name_plural': 'About Banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CourseBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='courses title')),
                ('courses_banner', models.ImageField(blank=True, null=True, upload_to='courses_banner/%Y/%m/%d/', verbose_name='courses banner')),
            ],
            options={
                'verbose_name': 'course banner',
                'verbose_name_plural': 'courses banner',
            },
        ),
        migrations.CreateModel(
            name='CourseSingleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_single_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='course_single_title')),
                ('course_single_banner', models.ImageField(blank=True, null=True, upload_to='courses_single_banner/%Y/%m/%d/', verbose_name='course_single_banner')),
            ],
            options={
                'verbose_name': 'Course single banner',
                'verbose_name_plural': 'Course single banners',
            },
        ),
        migrations.CreateModel(
            name='CSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours', models.CharField(max_length=50, verbose_name='hours')),
                ('calories_count', models.PositiveIntegerField(verbose_name='calories count')),
                ('type_calories', models.CharField(max_length=50, verbose_name='type calories')),
                ('workout_count', models.PositiveIntegerField(verbose_name='workout count (%)')),
                ('type_workout', models.CharField(max_length=50, verbose_name='type workout')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name': 'Course single',
                'verbose_name_plural': 'Course single',
            },
        ),
        migrations.CreateModel(
            name='GalleryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='sub title')),
            ],
            options={
                'verbose_name': 'gallery main',
                'verbose_name_plural': 'gallery main',
            },
        ),
        migrations.CreateModel(
            name='OurTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('achievement', models.CharField(max_length=100, verbose_name='achievement')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Our trainer',
                'verbose_name_plural': 'Our trainer',
            },
        ),
        migrations.CreateModel(
            name='PopularCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_time', models.TimeField(verbose_name='from time')),
                ('to_time', models.TimeField(verbose_name='to time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.category', verbose_name='course')),
            ],
            options={
                'verbose_name': 'popular course',
                'verbose_name_plural': 'popular courses',
            },
        ),
        migrations.CreateModel(
            name='PopularTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(upload_to='popular_people/%Y/%m/%d/', verbose_name='1 image')),
                ('image2', models.ImageField(upload_to='popular_people2/%Y/%m/%d/', verbose_name='2 image')),
                ('started', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='started')),
                ('people_about', ckeditor_uploader.fields.RichTextUploadingField(max_length=50, verbose_name='people about')),
            ],
            options={
                'verbose_name': 'Popular Trainer',
                'verbose_name_plural': 'Popular Trainers',
            },
        ),
        migrations.CreateModel(
            name='TrainerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='trainer title')),
                ('trainer_banner', models.ImageField(blank=True, null=True, upload_to='trainer_banner/%Y/%m/%d/', verbose_name='trainer banner')),
            ],
            options={
                'verbose_name': 'trainer banner',
                'verbose_name_plural': 'trainer banners',
            },
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'week',
                'verbose_name_plural': 'weeks',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TrainerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='some_value', upload_to='TrainerGallery/')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ourtrainer', verbose_name='gallery')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='PopularCourseGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='some_value', upload_to='PopularCourseGallery/')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.popularcourse', verbose_name='gallery')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
            },
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='weeks',
            field=models.ManyToManyField(to='pages.weeks', verbose_name='weeks'),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=50, verbose_name='full_name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.popularcourse', verbose_name='name')),
            ],
            options={
                'verbose_name': 'mentor',
                'verbose_name_plural': 'mentors',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='some_value', upload_to='about_gallery/%Y/%m/%d/', verbose_name='image')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.gallerymain')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
                ('students', models.PositiveIntegerField(verbose_name='students')),
                ('shift', models.CharField(max_length=50, verbose_name='shift')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
