# Generated by Django 4.1.3 on 2022-11-25 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populartrainer',
            name='started',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='started'),
        ),
    ]
