# Generated by Django 4.1.3 on 2022-11-25 11:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_populartrainer_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populartrainer',
            name='people_about',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, verbose_name='people about'),
        ),
    ]
