# Generated by Django 4.1.3 on 2022-11-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_weeks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourtrainer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='trainergallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ourtrainer', verbose_name='gallery'),
        ),
    ]
