# Generated by Django 4.1.3 on 2022-11-18 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_populartrainer_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populartrainer',
            name='started',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='started'),
        ),
    ]
