# Generated by Django 4.1.3 on 2022-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_populartrainer_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populartrainer',
            name='started',
            field=models.PositiveIntegerField(max_length=4, verbose_name='started'),
        ),
    ]
