# Generated by Django 4.1.3 on 2022-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_ourtrainer_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourtrainer',
            name='image',
            field=models.ImageField(default=None, upload_to='trainer'),
            preserve_default=False,
        ),
    ]
