# Generated by Django 4.1.3 on 2022-11-18 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_populartrainer_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='about_gallery/%Y/%m/%d/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'gallery library',
                'verbose_name_plural': 'gallery libraries',
            },
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AlterField(
            model_name='populartrainer',
            name='started',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='started'),
        ),
    ]
