# Generated by Django 4.1.3 on 2022-11-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_category_coursebanner_mentor_ourtrainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourtrainer',
            name='image',
        ),
        migrations.CreateModel(
            name='TrainerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='some_value', upload_to='TrainerGallery/')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.ourtrainer', verbose_name='gallery')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
            },
        ),
    ]
