# Generated by Django 4.1.3 on 2022-11-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_ourtrainer_image_trainergallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcourse',
            name='main_banner',
        ),
    ]
