# Generated by Django 4.1.3 on 2022-11-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_popularcourse_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcourse',
            name='from_time',
            field=models.TimeField(verbose_name='from time'),
        ),
        migrations.AlterField(
            model_name='popularcourse',
            name='to_time',
            field=models.TimeField(verbose_name='to time'),
        ),
    ]
