# Generated by Django 4.1.3 on 2022-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_popularcourse_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcourse',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
