# Generated by Django 4.1.3 on 2022-11-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_popularcourse_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcourse',
            name='title',
        ),
    ]
