# Generated by Django 4.1.3 on 2022-11-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_popularcourse_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSingleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_single_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='course_single_title')),
                ('course_single_banner', models.ImageField(blank=True, null=True, upload_to='courses_single_banner/%Y/%m/%d/', verbose_name='course_single_banner')),
            ],
            options={
                'verbose_name': 'Course Single Banner',
                'verbose_name_plural': 'Course Single Banners',
            },
        ),
        migrations.CreateModel(
            name='CSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours', models.CharField(max_length=50, verbose_name='hours')),
                ('calories_count', models.PositiveIntegerField(verbose_name='calories count')),
                ('type_calories', models.CharField(max_length=50, verbose_name='type calories')),
                ('workout_count', models.PositiveIntegerField(verbose_name='workout count (%)')),
                ('type_workout', models.CharField(max_length=50, verbose_name='type workout')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name': 'Course Single',
                'verbose_name_plural': 'Course Single',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
                ('students', models.PositiveIntegerField(verbose_name='students')),
                ('shift', models.CharField(max_length=50, verbose_name='shift')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
