# Generated by Django 4.1.3 on 2022-11-25 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact title')),
                ('contact_banner', models.ImageField(blank=True, null=True, upload_to='media/contact_banner', verbose_name='contact banner')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=13)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactSendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='sub title')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('massage', models.TextField(verbose_name='massage')),
            ],
            options={
                'verbose_name': 'contact send',
                'verbose_name_plural': 'contact sends',
            },
        ),
    ]
