# Generated by Django 4.1.3 on 2022-11-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactsendmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsendmodel',
            options={'verbose_name': 'contact send', 'verbose_name_plural': 'contact sends'},
        ),
    ]
