# Generated by Django 4.1.3 on 2022-11-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactsendmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsendmodel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='contactsendmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
    ]
