# Generated by Django 4.1.3 on 2022-11-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('author_name', models.CharField(max_length=50, verbose_name='author name')),
                ('job', models.CharField(max_length=50, verbose_name='job')),
            ],
            options={
                'verbose_name': 'What people say',
                'verbose_name_plural': 'What people says',
            },
        ),
    ]
