# Generated by Django 4.1.3 on 2022-11-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
