# Generated by Django 4.1.3 on 2022-11-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='banner_title',
            new_name='blog_title',
        ),
    ]
