# Generated by Django 4.1.3 on 2022-11-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_banner_title_postmodel_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='blog_banner',
        ),
    ]
