# Generated by Django 4.1.3 on 2022-11-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin')),
                ('pinterest', models.URLField(blank=True, null=True, verbose_name='pinterest')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.postmodel', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'Blog contact',
                'verbose_name_plural': 'Blog contact',
            },
        ),
    ]
