# Generated by Django 4.1.3 on 2022-11-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcontact',
            options={'ordering': ('-pk',), 'verbose_name': 'Blog contact', 'verbose_name_plural': 'Blog contact'},
        ),
    ]
