# Generated by Django 4.1.3 on 2022-11-18 11:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_location', models.CharField(blank=True, max_length=20, null=True, verbose_name='title location')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('support_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='support_phone')),
                ('support_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='support_phone')),
            ],
            options={
                'verbose_name': 'footer',
                'verbose_name_plural': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='club name')),
                ('home_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=40, null=True, verbose_name='home title')),
                ('home_banner', models.ImageField(blank=True, null=True, upload_to='home_banner/%Y/%m/%d/', verbose_name='home banner')),
                ('home_cat_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='home category name')),
                ('cat_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='brand name')),
                ('nav_item', models.CharField(blank=True, max_length=10, null=True, verbose_name='navbar item')),
                ('phone_number', models.CharField(blank=True, max_length=9, null=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'navbar',
                'verbose_name_plural': 'navbar',
            },
        ),
        migrations.CreateModel(
            name='PeopleSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('sub_title', models.CharField(max_length=50, verbose_name='sub_title')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('author_name', models.CharField(max_length=50, verbose_name='author_name')),
                ('job', models.CharField(max_length=50, verbose_name='job')),
            ],
            options={
                'verbose_name': 'What people say',
                'verbose_name_plural': 'What people says',
            },
        ),
    ]
