# Generated by Django 4.1.3 on 2022-11-24 22:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_location', models.CharField(blank=True, max_length=20, null=True, verbose_name='title location')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('support_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='support phone')),
                ('support_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='support mail')),
            ],
            options={
                'verbose_name': 'footer',
                'verbose_name_plural': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='club name')),
                ('home_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=155, null=True, verbose_name='home title')),
                ('home_banner', models.ImageField(blank=True, null=True, upload_to='home_banner/%Y/%m/%d/', verbose_name='home banner')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='brand name')),
                ('nav_item', models.CharField(blank=True, max_length=10, null=True, verbose_name='navbar item')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'navbar',
                'verbose_name_plural': 'navbar',
            },
        ),
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_cat_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='home category name')),
                ('cat_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='category description')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.home')),
            ],
            options={
                'verbose_name': 'home category',
                'verbose_name_plural': 'home categories',
                'ordering': ('-id',),
            },
        ),
    ]
