# Generated by Django 4.1.3 on 2022-11-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='support_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='support mail'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='support_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='support phone'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone number'),
        ),
    ]
