# Generated by Django 4.1.3 on 2022-11-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_home_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='cat_number',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
