# Generated by Django 4.1.3 on 2022-11-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_footer_support_mail_alter_footer_support_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplesay',
            name='sub_title',
        ),
        migrations.AlterField(
            model_name='peoplesay',
            name='author_name',
            field=models.CharField(max_length=50, verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='peoplesay',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
