# Generated by Django 4.1.3 on 2022-11-23 08:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_peoplesay_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=155, null=True, verbose_name='home title'),
        ),
    ]
