# Generated by Django 4.1.3 on 2022-11-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecategory_cat_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecategory',
            options={'verbose_name': 'home category', 'verbose_name_plural': 'home categories'},
        ),
    ]
