# Generated by Django 4.1.3 on 2022-11-25 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecategory',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
