# Generated by Django 4.1.3 on 2022-11-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_home_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='cat_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_cat_name',
        ),
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_cat_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='home category name')),
                ('cat_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='category description')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.home')),
            ],
            options={
                'verbose_name': 'home category',
                'verbose_name_plural': 'home categories',
            },
        ),
    ]
