# Generated by Django 4.1.3 on 2022-11-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_home_cat_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecategory',
            options={'ordering': ('-id',), 'verbose_name': 'home category', 'verbose_name_plural': 'home categories'},
        ),
    ]
