# Generated by Django 4.1.3 on 2022-11-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homecategory_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeopleSay',
        ),
    ]
